sonar.projectKey=elliot-heyse-private_r0-m1-s1-nextjs
sonar.organization=elliot-heyse-private
sonar.projectName=elliot-heyse-private-r0-m1-s1-nextjs
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/*.d.ts
sonar.coverage.exclusions=**/node_modules/**,**/.next/**,**/*.d.ts,**/*.test.*,**/*.spec.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info